# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# S3 Repository Demo is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

addons:


# Chrome Webdriver fails if not on sudo
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: true

dist: trusty # Chrome driver fails if not trusty dist

notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: never # default: always

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - docker

env:
  global:
    - LIVELINESS_TIMEOUT=300
    - OAREPO_ADMIN_PASSWORD=Tr4vi1SWasH3r3!
    - OAREPO_ADMIN_USER=admin@oarepo.org
    - INVENIO_SECRET_KEY=This1SSoooS3cr#t
    - INVENIO_WSGI_PROXIES=2
    - INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://cesnet-demo:demo-pass@db/cesnet-demo
    - INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/
    - INVENIO_CACHE_TYPE=redis
    - INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1
    - INVENIO_CACHE_REDIS_URL=redis://cache:6379/0
    - INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3
    - INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/
    - INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2
    - INVENIO_SEARCH_ELASTIC_HOSTS='es:9200'
    - INVENIO_CELERY_LOG_LEVEL=INFO
    - SERVER_NAME=127.0.0.1:5001
    - JSONSCHEMAS_HOST=cesnet.cz
    - APP_ALLOWED_HOSTS=frontend,localhost,127.0.1.1
    - SEARCH_INDEX_PREFIX=demo-
  matrix:
    - OAREPO_VERSION=3.3.0 OAREPO_ES_VERSION=es7

python:
  - "3.8"

before_install:
  # Stop default travis services
  - "sudo service mysql stop"
  - "sudo service postgresql stop"
  # Start docker services
  - "./docker/build-images.sh"
  - "docker-compose up -d"
  # Chrome webdriver for Selenium
  - "travis_retry pip install --upgrade pip setuptools py pipenv"
  - "travis_retry pip install twine wheel coveralls"
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - "docker-compose --version"


install:
  - docker-compose -f docker-compose.deploy.yml build
  - docker-compose -f docker-compose.full.yml build
  - docker-compose -f docker-compose.full.yml up --no-start
  - docker-compose -f docker-compose.deploy.yml up --abort-on-container-exit

before_script:
  # Allow services running inside docker to start
  - "./docker/wait-for-services.sh"

script:
  - docker-compose -f docker-compose.full.yml start
  - docker ps
  - timeout ${LIVELINESS_TIMEOUT} bash -c 'while [[ "$(curl -k -sf -o /dev/null -w ''%{http_code}'' https://localhost/.well-known/heartbeat/liveliness)" != "200" ]]; do docker logs cesnetdemo_web-api_1; sleep 5; done'
  - docker-compose -f docker-compose.full.yml stop

after_success:
  - coveralls
